config/routes.rb
ExpenseTrackTool::Application.routes.draw do
  devise_for :users, :controller => { sessions: 'devise/sessions'}
  root :to => "expenses#index"

  
  get "category_new" => "categories#new", :as => "category_new"
  post "category_create" => "categories#create", :as => "category_create"
  resources :reports do
    collection do
      get :index
      get :result
    end
  end
 
    resources :categories do
      resources :expenses
    end
    resources :expenses
    
  
end

  # match ':controller(/:action(/:id))(.:format)'

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :expenses
  belongs_to :user
  attr_accessible :description, :name, :user_id
  validates :name,  :presence => true
  validates :description, :presence => true
end

app/models/expense.rb
class Expense < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  attr_accessible :category_id, :comments, :cost, :item_name, :spent_on, :user_id
  self.per_page = 5
  validate :validate_spent_on
  validates :cost, :format => { :with => /^\d+??(?:\.\d{0,2})?$/ }, :numericality => {:greater_than => 0, :less_than => 1000000}
  
  def validate_spent_on 
    puts "spent_on.inspect >> #{spent_on.inspect}"
    errors.add(:spent_on, "date should not be greater than current date") if spent_on.present? && spent_on.to_date > Date.today
  end
  def convert_date
    spent_on = Date.parse(spent_on)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name
  #attr_accessible :email, :password, :password_confirmation
  has_many :expenses
  has_many :categories
  #attr_accessor :password
  
  #validates_confirmation_of :password
  #validates_presence_of :password, :on => :create
  #validates_presence_of :email
  
 
  def name
    return "#{first_name} #{last_name}".strip if first_name.present? || last_name.present?
    email
  end
  #def self.authenticate(email, password) 
    #user = find_by_email(email) 

    #puts user  #this returns nil so my class is never able to authenticate the user

   #return nil if user.nil? 
    #return user if user.password?(password)
  #end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :authenticate_user!
  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(params[:category])
    @category.user = current_user
    if @category.save
      redirect_to categories_path, :notice => "New category saved"
    else
      render 'new'
    end
  end
  def index
    @categories = current_user ? current_user.categories : Category.all
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_filter :authenticate_user!
  def new   
    @expense = Expense.new
    @expense.category_id = params[:category_id] if params[:category_id]
  end
  
  def create
      @expense = Expense.new params[:expense]
      @expense.user = current_user
      respond_to do |format|
        if @expense.save
          format.html { redirect_to(@expense, :notice => 'Expense was successfully created.') }
          format.json { render json: @expense, status: :created, location: @expense}
        else
          format.html { render action: "new"}
          format.json { render json: @expense.errors, status: :unprocessable_entity, :notice => 'Error occured' }
       end
      end
  end
  
  def show
    @expense = Expense.find(params[:id])
  end
  def index
    if current_user
      @expenses = current_user.expenses
      @expenses = @expenses.paginate(page: params[:page])
    end
  end
  
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
before_filter :authenticate_user!
  def index
    
  end
  
  def result
    if params[:spent_on_from_date].present? && params[:spent_on_to_date].present?
    @expenses = Expense.where("spent_on >= ? and user_id = ?", Date.parse(params[:spent_on_from_date]), current_user.id)
    @expenses = Expense.where("spent_on <= ? and user_id = ?", Date.parse(params[:spent_on_to_date]), current_user.id)
    @expenses = @expenses.where("category_id = ?", params[:category_id]) if params[:category_id].present?
    @expenses = @expenses.paginate(:page => params[:page])
    render :action => :index
    else
      redirect_to reports_path, :notice => "Please select From and To dates"
    end
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper

end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
  
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.erb
<div style="margin:auto;width: 80%;padding: 0px">
    <div style = "display: inline;padding-bottom: 20px">
        <h3 style="display: inline;padding-right: 750px">Categories</h3>  
       <%= link_to 'new category', new_category_path, :class => "btn btn-primary" %>
     </div>
     <br />
    <table class="table table-bordered">
      <tr>
       <th>Category Name</th>
       <th>Description</th>
      </tr>
     <% if @categories.present? %>
       <% @categories.each do |category| %>
           <tr>
             <td>
                 <%= category.name %> <%= link_to 'new expense', new_category_expense_path(category), :class => "popover-test", :rel => "popover", :title => nil, :"data-content" =>"Create a New Expense through this link for an existing Category" %>
                 </td>       
             <td><%= category.description %></td>
           </tr>
       <% end %>
     <% end %>
    </table>
</div>

app/views/categories/new.html.erb
<div class="hero-unit" style="margin:auto;width: 70%;">
    <h2>New category creation</h2>
    <%= form_for @category do |f| %>
        <% if @category.errors.any? %>
          <div class="error_messages">
            <h2>Form is invalid</h2>
            <ul>
              <% for message in @category.errors.full_messages %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <p>
          <%= f.label :name %>
          <%= f.text_field :name, :required => true %>
        </p>
        <p>
          <%= f.label :description %>
          <%= f.text_field :description, :required => true %>
        </p>
        <%= f.submit "create", :class => "btn btn-primary" %></p>
    <% end %>
</div>

app/views/expenses/index.html.erb
<div style="margin:auto;width: 90%;">    
<% if current_user %>
     <div style = "margin-left:10px;display: inline;padding-bottom: 30px">
       <h2 style="display: inline;padding-right: 800px;">Expenses</h2>  
       <%= link_to 'new expense', new_expense_path, :class => "btn btn-primary", :style => "display:inline" %>
     </div>
     <br />
     <% if @expenses.present? %>
     <div style="padding-top: 10px"> 
  <table class="table table-bordered">
      <tr>
       <th>Item Name</th>
       <th>Category Name</th>
       <th>Cost</th>
       <th>Spent On</th>
      </tr>      
         <% @expenses.each do |expense| %>
           <tr>
             <td><%= expense.item_name %></td>
             <td><%= expense.category.try(:name) %></td>
             <td><%= expense.cost %></td>
             <td><%= expense.spent_on %></td>
           </tr>           
         <% end %>
    </table>
         <%= will_paginate @expenses if @expenses %>
    </div>
         <% else %>
         <div class="alert">
             <%= flash[:alert] %>
             <h4>You didnot enter the expenses, please enter your monthly expenses through button "new expense"</h4>
         </div>
       <% end %>
  <% else %>
 <div class="container" width="300px">
     <h1 style= "color:green">Expense Tracking :</h1>
<h3>
 Expense Tracking is a full-featured finance software that you can carry in your pocket.
It is a powerful and easy to use program that will help you track and understand your personal finance.
Expense Tracking brings all your financial accounts together,
categorizes your transactions, tracks all your bills,
lets you set budgets and helps you achieve your savings goals. In just minutes, 
you’ll see where your money is going and where you could save money.
</h3>
 </P>
<% end %>
</div>

app/views/expenses/new.html.erb
<div class="hero-unit" style="margin:auto;width: 70%;">
    <div style="padding-top: 0px">
        <h2 style="padding-top: 0px">New Expense creation</h2>
    </div>
 <%= form_for @expense do |f| %>
    <% if  @expense.errors.any? %>
      <div id="error_explanation" style= color:red;>
        <h2><%= pluralize(@expense.errors.count, "error") %> prohibited this expense from being saved:</h2>
        <ul>
          <% @expense.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
        <span>
          <%= f.label :category_id %>
          <span>
            <%= f.collection_select :category_id, current_user.categories, :id, :name, option = {:selected => @expense.category_id}, {:style =>"float:left" } %>
            <h4 style="display: inline;padding-left: 30px">create a new category through this button</h4><%= link_to 'new category', new_category_path, :class => "btn btn-primary", :style => "display:inline" %>
          </span>
        </span>  
         <p style="padding-top: 20px">
          <%= f.label :item_name %>
          <%= f.text_field :item_name, :required => true %>
         </p>
         <p>
          <%= f.label :cost %>
          <%= f.text_field :cost, :required => true %>
         </p>
         <p>
          <%= f.label :spent_on %>
         <%= f.text_field :spent_on %>
         </p>
         <p>
          <%= f.label :comments %>
          <%= f.text_area(:comments, {:cols => 10, :rows => 5})%>
         </p>
    <%= f.submit "create", :class => "btn btn-primary"%>
  <% end %>
</div>
<script>
$(function() {
  $("#expense_spent_on").datepicker({
        showButtonPanel: true,
        dateFormat: "dd/mm/yy"
  });
});
</script>

app/views/expenses/show.html.erb
<div class="hero-unit" style="margin:auto;width: 70%;">
    <table class="table table-striped table-bordered table-condensed">
      <tr>
            <td>Category</td>
            <td><%= @expense.category_id %></td>
      </tr>
      <tr>
            <td>Item Name</td>
            <td><%= @expense.item_name %></td>
      </tr>
      <tr>
            <td>Cost</td>
            <td><%= @expense.cost %></td>
      </tr>
      <tr>
            <td>Spent On</td>
            <td><%= @expense.spent_on %></td>
      </tr>
      <tr>
            <td>Comments</td>
            <td><%= @expense.comments %></td>
      </tr>
    </table>
    <p style="width:100%; text-align: center">
    <%= link_to 'back', expenses_path, :class => "btn btn-primary" %>
    </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
      <title>ExpenseTrackTool</title>
      <%= stylesheet_link_tag    "application", :media => "all" %>
      <%= javascript_include_tag "application" %>
      <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="navbar navbar-inverse" style="width: 100%">
    <div class="navbar-inner"> 
          <ul class="nav">
                <li style="padding-left:120px"><%= link_to 'Home', root_path %></li>
                <li><%= link_to 'Expenses', expenses_path %></li>
                <li><%= link_to 'Report', reports_path %></li>
                <li><%= link_to 'Category', categories_path %></li>
            <% if user_signed_in? %>
              <li id="fat-menu" class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %><b class="caret"></b>
              </a>
                <ul class="dropdown-menu">
                        <li><%= link_to "Edit Profile", edit_user_registration_path(current_user.id) %></li>
                        <li class="divider"></li>
                        <li>
                         <%= link_to'Logout', destroy_user_session_path, :method=> 'delete' %>
                        </li>
                    </ul>
                </li>
            <%else%>
              <li><%= link_to 'Login', new_user_session_path %></li> 
              <li><%= link_to'Sign Up', new_user_registration_path %></li>
            <% end %> 
         </ul>
    </div>
 </div>
<div id="flash">
   <% unless flash[:alert].blank? %>
     <div class="alert">
         <a href="#" data-dismiss="alert" class="close">×</a>
         <%= flash[:alert] %>
     </div>
   <% end %>
   <% if content_for?(:message) %>
        <div class="alert" style ="margin:auto; width: 80px">
            <a href="#" data-dismiss="alert" class="close">×</a>
            <%= yield(:message) %>
        </div>="alert" class="close">×</a>
            <%= yield(:message) %>
        </div>
    <%end %>
    
    <% unless flash[:notice].blank? %>
    <div class="alert alert-info" style = "<%= 'border-top:0;text-align: center;' if flash[:alert] || yield(:message) %>">
        <a href="#" data-dismiss="alert" class="close">×</a>
        <%= flash[:notice] %>
    </div>
    <% end %>
</div>

<%= yield %>
  <div class="navbar navbar-fixed-bottom">
    <div class="navbar-inner">
      <div class="width-constraint clearfix" style="background: black; font-family: Verdana;height: 40px">
        <p class="muted credit"><center>YourApp v1.0.0, ©2013 • CONFIDENTIAL ALL RIGHTS RESERVED</center></p>
      </div>
    </div>
  </div>
  </body>
</html>

app/views/reports/index.html.erb
<script>
    $(function() {
        $( "#spent_on_from_date" ).datepicker({
            showButtonPanel: true,
            dateFormat: "dd/mm/yy"
        });
        $( "#spent_on_to_date" ).datepicker({
            showButtonPanel: true,
            dateFormat: "dd/mm/yy"
        });
    });
</script>  
<div class="hero-unit" style="margin:auto;width: 80%;height:60px;line-height:30px;padding:10px">
  <%= form_tag "/reports/result", :method => :get do %>
        <div style="width:25%;float:left;">
          <%= label_tag :spent_on_from_date %>
         <%= text_field_tag :spent_on_from_date, params[:spent_on_from_date] %>
        </div>
        <div style="width:25%;float:left;">
          <%= label_tag :spent_on_to_date %>
         <%= text_field_tag :spent_on_to_date, params[:spent_on_to_date] %>
        </div>
        <div style="width:25%;float:left;">
          <%= label_tag :category_id %>
          <%= select_tag 'category_id', options_for_select([["--All--", ""]] + current_user.categories("id, name").collect{ |c| [c.name, c.id] }, params[:category_id]) %>
        </div>
        <div style="padding: 24px">
          <%= submit_tag "submit", :class => "btn btn-primary" %>
        </div>
   <% end %>
</div>
<% if @expenses.present? %>
<div style="padding-left: 130px;padding-right: 130px;padding-top: 20px">
<table class="table table-bordered">
      <tr>
       <th>Item name</th>
       <th>Category name</th>
       <th>Cost</th>
       <th>Spent On</th>
      </tr>
      <% total = 0 %>
     <% @expenses.each do |expense| %>
         <% total += expense.cost %>
       <tr>
         <td><%= expense.item_name %></td>
         <td><%= expense.category.try(:name) %></td>
         <td><%= expense.cost %></td>
         <td><%= expense.spent_on %></td>
       </tr>
     <% end %>    
         <tr><td colspan = 4>The total cost of all expenses = <%= total %></td></tr>
   <% end %>
</table>
<%= will_paginate @expenses if @expenses %>
</div>